esphome:
  name: toilet
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: toilet
            level: !lambda 'return level / 100.0;'

captive_portal:

button:
  - platform: restart
    name: "Toliet Flusher Restart"

output:
  - platform: ledc
    pin: GPIO13
    id: gpio_13_servo
    frequency: 50 Hz
    
servo:
  - id: toilet
    output: gpio_13_servo
